### ISSUE TITLE
User Stories - Car safety

### ISSUE THREAD

**Issue by shabonout** [DIT112-V19/group-08#11]
## Description
As a driver, I would like my car not to hit any other car or object so that I would not pay for reparations for my or other cars
As a driver, I would like my car not to be scratched so that I would not pay for reparations

## Acceptance Criteria
Implement autonomous obstacle avoidance, car should successfully avoid collision at least 9 times out of 10

**Comment by TheMartyLekekas** [comment]
Car stops successfully every time there is an obstacle in its way

**Comment by TheMartyLekekas** [comment]
Car stops every time there is an obstacle in its way
