### ISSUE TITLE
User Stories - Find parking spot

### ISSUE THREAD

**Issue by shabonout** [DIT112-V19/group-08#26]
## Description
As a driver I want my car to find an empty parking spot big enough for the car so that the car would fit and have enough space to exit the parking spot

## Acceptance Criteria
The car identifies a parking spot that is long as the length of the car plus the amount of extra space needed for exiting the parking spot

**Comment by TheMartyLekekas** [comment]
Car measures the size of free spaces between two objects and parks only in big enough spaces
